name: Build CI wheels

on:
  push:
    branches:
      - main
      - v[0-9]+.[0-9]+.x
    tags:
      - v*

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/checkout@v2
        name: Install java
        with:
          java-version: 1.8

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.6'
      
      - name: Install python depencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install certifi cibuildwheel==2.2.2
          python -m pip install -r requirements.txt
      
#      - name: Build MacOS wheel
#        if: matrix.os == 'macos-latest'
#        env:
#          CIBW_BUILD: cp36-macosx_x86_64
#          CIBW_BEFORE_ALL: brew install libomp		
#          CIBW_ENVIRONMENT: >
#            SSL_CERT_FILE="combined_cert.pem"
#            REQUESTS_CA_BUNDLE="combined_cert.pem"
#        run: python -m cibuildwheel --platform macos --output-dir wheelhouse

      - name: Install linux wheels
        env:
          CIBW_BUILD: "cp36-manylinux_x86_64 cp37-manylinux_x86_64 cp38-manylinux_x86_64 cp39-manylinux_x86_64"
          CIBW_ENVIRONMENT: >
            SSL_CERT_FILE="combined_cert.pem"
            REQUESTS_CA_BUNDLE="combined_cert.pem"
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
